CREATE TABLE "ACTIONMAP" (
  "ID" INT NOT NULL GENERATED ALWAYS AS IDENTITY ,
  "ACTIONID" VARCHAR(100) NOT NULL DEFAULT '',
  "DIRID" INT DEFAULT 0,
  "SUBDIR" VARCHAR(20) DEFAULT NULL,
  "CLASSNAME" VARCHAR(80) NOT NULL DEFAULT '',
  "PERMISSIONORDER" INT NOT NULL DEFAULT -1,
  "PARAMS" CLOB,
  "MENU" VARCHAR(100) DEFAULT NULL,
  "MEMO" CLOB,
  "CREATETIME" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("ID")
);
CREATE UNIQUE INDEX ACTIONMAP_IDX ON APP."ACTIONMAP"("ACTIONID","DIRID","SUBDIR");
CREATE INDEX ACTIONMAP_CLASSNAME ON APP."ACTIONMAP"("CLASSNAME");
CREATE INDEX ACTIONMAP_CREATETIME ON APP."ACTIONMAP"("CREATETIME");
CREATE INDEX ACTIONMAP_MENU ON APP."ACTIONMAP"("MENU")