CREATE TABLE "DATASOURCE" (
  "JNDINAME" VARCHAR(20) NOT NULL DEFAULT '',
  "HOST" VARCHAR(30) NOT NULL DEFAULT '',
  "DRIVER" VARCHAR(60) NOT NULL DEFAULT 'com.mysql.jdbc.Driver',
  "DBURL" VARCHAR(100) NOT NULL DEFAULT '',
  "USERNAME" VARCHAR(15) NOT NULL DEFAULT '',
  "PWD" VARCHAR(20) DEFAULT '',
  "MAXCONNECTION" INT NOT NULL DEFAULT 100,
  "MINCONNECTION" INT NOT NULL DEFAULT 5,
  "TIMEOUTVALUE" INT NOT NULL DEFAULT 600000,
  "TESTSQL" VARCHAR(50) NOT NULL DEFAULT 'SELECT 1',
  "MAXSTATEMENT" INT NOT NULL DEFAULT 50,
  PRIMARY KEY ("JNDINAME","HOST")
)