CREATE TABLE "DEMO" (
  "ID" INT NOT NULL GENERATED ALWAYS AS IDENTITY ,
  "NAME" VARCHAR(20) NOT NULL DEFAULT '',
  "AGE" INT NOT NULL DEFAULT 0,
  "SEX" SMALLINT NOT NULL DEFAULT 1,
  "MOBILE" VARCHAR(20) DEFAULT NULL,
  "REGTIME" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "MEMO" CLOB,
  PRIMARY KEY ("ID")
)