CREATE TABLE "HIBERNATEMAP" (
  "ID" INT NOT NULL GENERATED ALWAYS AS IDENTITY ,
  "HOST" VARCHAR(30) NOT NULL DEFAULT '',
  "TITLE" VARCHAR(60) NOT NULL DEFAULT '',
  "CLASSNAME" VARCHAR(80) NOT NULL DEFAULT '',
  "DATASOURCE" VARCHAR(20) NOT NULL DEFAULT '',
  "TABLENAME" VARCHAR(20) DEFAULT NULL,
  "CATALOGNAME" VARCHAR(20) DEFAULT NULL,
  "XMLMAP" CLOB,
  "CREATETIME" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("ID")
);
CREATE UNIQUE INDEX HIBERNATEMAP_IDX ON APP."HIBERNATEMAP"("HOST","CLASSNAME","DATASOURCE");
CREATE INDEX HIBERNATEMAP_TITLE ON APP."HIBERNATEMAP"("TITLE");
CREATE INDEX HIBERNATEMAP_TABLENAME ON APP."HIBERNATEMAP"("TABLENAME");
CREATE INDEX HIBERNATEMAP_CREATETIME ON APP."HIBERNATEMAP"("CREATETIME");
CREATE INDEX HIBERNATEMAP_CATALOGNAME ON APP."HIBERNATEMAP"("CATALOGNAME")