CREATE TABLE "SVNCODES"(
"ID" INT NOT NULL GENERATED ALWAYS AS IDENTITY ,
"HOST" VARCHAR(30) NOT NULL DEFAULT '',
"TITLE" VARCHAR(60) DEFAULT NULL,
"URL" VARCHAR(200),
"DIRNAME" VARCHAR(35)  DEFAULT 'NEWDIR' NOT NULL,
"USERNAME" VARCHAR(20),
"PASSWORD" VARCHAR(50),
"DIRTYPE" SMALLINT  DEFAULT 0 NOT NULL,
"MESSAGE" CLOB,
PRIMARY KEY ("ID")
);
CREATE UNIQUE INDEX SVNCODES_IDX ON APP."SVNCODES"("HOST","URL");
CREATE INDEX SVNCODES_TITLE ON APP."SVNCODES"("TITLE");
CREATE INDEX SVNCODES_DIRNAME ON APP."SVNCODES"("DIRNAME");
CREATE INDEX SVNCODES_DIRTYPE ON APP."SVNCODES"("DIRTYPE")