CREATE TABLE "WEBDIRECTORY" (
  "ID" INT NOT NULL GENERATED ALWAYS AS IDENTITY ,
  "HOST" VARCHAR(30) NOT NULL DEFAULT '',
  "DIRNAME" VARCHAR(20) NOT NULL DEFAULT '',
  "TITLE" VARCHAR(60) DEFAULT NULL,
  "CLASSNAME" VARCHAR(80) DEFAULT NULL,
  "DEFAULTPAGE" VARCHAR(20) DEFAULT NULL,
  "IPLIST" VARCHAR(100) DEFAULT NULL,
  "LOGINTYPE" SMALLINT NOT NULL DEFAULT 0,
  "PARAMS" CLOB,
  "LOGNAME" VARCHAR(20) NOT NULL DEFAULT 'system',
  "CHARSET" VARCHAR(20) DEFAULT NULL,
  "MEMO" CLOB,
  "CREATETIME" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("ID")
);

CREATE UNIQUE INDEX WEBDIRECTORY_IDX ON APP."WEBDIRECTORY"("HOST","DIRNAME");
CREATE INDEX WEBDIRECTORY_TITLE ON APP."WEBDIRECTORY"("TITLE");
CREATE INDEX WEBDIRECTORY_CLASSNAME ON APP."WEBDIRECTORY"("CLASSNAME");
CREATE INDEX WEBDIRECTORY_LOGINTYPE ON APP."WEBDIRECTORY"("LOGINTYPE")