CREATE TABLE `Mount` (
  `mountId` INTEGER(11) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `path` VARCHAR(50) DEFAULT NULL COMMENT '',
  `quota` BIGINT(20) DEFAULT NULL COMMENT '',
  `createTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`mountId`),
  UNIQUE KEY `path` (`path`)
);
