CREATE TABLE "ACTIONMAP" (
"ID" NUMBER(8)  NOT NULL,
"ACTIONID" VARCHAR2(100)  DEFAULT NULL,
"DIRID" NUMBER(8)  DEFAULT '0' NOT NULL,
"SUBDIR" VARCHAR2(20) DEFAULT NULL,
"CLASSNAME" VARCHAR2(80)  DEFAULT NULL,
"PERMISSIONORDER" NUMBER(2)  DEFAULT -1 NOT NULL,
"PARAMS" CLOB,
"MENU" VARCHAR2(100) DEFAULT 'NA',
"MEMO" CLOB,
"CREATETIME" TIMESTAMP  DEFAULT CURRENT_TIMESTAMP NOT NULL,
PRIMARY KEY ("ID")
);
--创建索引
CREATE UNIQUE INDEX "IX_ACTIONMAP_ACTIONID" ON "ACTIONMAP" ("ACTIONID", "DIRID", "SUBDIR");
CREATE INDEX "IX_ACTIONMAP_CLASSNAME" ON "ACTIONMAP" ("CLASSNAME");
CREATE INDEX "IX_ACTIONMAP_MENU" ON "ACTIONMAP" ("MENU");
CREATE INDEX "IX_ACTIONMAP_CREATETIME" ON "ACTIONMAP" ("CREATETIME");
--添加注释
COMMENT ON COLUMN "ACTIONMAP"."ID" IS '标识';
COMMENT ON COLUMN "ACTIONMAP"."ACTIONID" IS 'ACTIONID';
COMMENT ON COLUMN "ACTIONMAP"."DIRID" IS '目录ID';
COMMENT ON COLUMN "ACTIONMAP"."SUBDIR" IS '相对于DIR的下一级目录';
COMMENT ON COLUMN "ACTIONMAP"."CLASSNAME" IS '类名';
COMMENT ON COLUMN "ACTIONMAP"."PERMISSIONORDER" IS '权限位';
COMMENT ON COLUMN "ACTIONMAP"."PARAMS" IS '配置';
COMMENT ON COLUMN "ACTIONMAP"."MENU" IS '菜单';
COMMENT ON COLUMN "ACTIONMAP"."MEMO" IS '备注';
COMMENT ON COLUMN "ACTIONMAP"."CREATETIME" IS '创建/修改时间';
--建立序列
CREATE SEQUENCE ACTIONMAP_SQ;
--建立触发器，以设置自动增量字段的值
CREATE OR REPLACE TRIGGER ACTIONMAP_TR
BEFORE INSERT ON ACTIONMAP
FOR EACH ROW
DECLARE
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT ACTIONMAP_SQ.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;