CREATE TABLE "DATASOURCE" (
"JNDINAME" VARCHAR2(20)  DEFAULT NULL,
"HOST" VARCHAR2(30)  DEFAULT NULL,
"DRIVER" VARCHAR2(60)  DEFAULT 'com.mysql.jdbc.Driver' NOT NULL,
"DBURL" VARCHAR2(100)  DEFAULT NULL,
"USERNAME" VARCHAR2(15)  DEFAULT NULL,
"PWD" VARCHAR2(20) DEFAULT NULL,
"MAXCONNECTION" NUMBER(4)  DEFAULT 100 NOT NULL,
"MINCONNECTION" NUMBER(4)  DEFAULT 5 NOT NULL,
"TIMEOUTVALUE" NUMBER(8)  DEFAULT 600000 NOT NULL,
"TESTSQL" VARCHAR2(30)  DEFAULT 'SELECT 1' NOT NULL,
"MAXSTATEMENT" NUMBER(4)  DEFAULT 50 NOT NULL,
PRIMARY KEY ("JNDINAME", "HOST")
);
--添加注释
COMMENT ON COLUMN "DATASOURCE"."JNDINAME" IS '数据库连接池名称';
COMMENT ON COLUMN "DATASOURCE"."HOST" IS '主机';
COMMENT ON COLUMN "DATASOURCE"."DRIVER" IS '数据库驱动类名';
COMMENT ON COLUMN "DATASOURCE"."DBURL" IS '数据库URL地址';
COMMENT ON COLUMN "DATASOURCE"."USERNAME" IS '账号';
COMMENT ON COLUMN "DATASOURCE"."PWD" IS '密码';
COMMENT ON COLUMN "DATASOURCE"."MAXCONNECTION" IS '最大连接数';
COMMENT ON COLUMN "DATASOURCE"."MINCONNECTION" IS '空闲时最小连接数';
COMMENT ON COLUMN "DATASOURCE"."TIMEOUTVALUE" IS '登录超时';
COMMENT ON COLUMN "DATASOURCE"."TESTSQL" IS '测试指令，交付程序的连接首先执行此激活指令，不填则不进行激活测试';
COMMENT ON COLUMN "DATASOURCE"."MAXSTATEMENT" IS '允许单个连接创建的最大声明数;0不限制';