CREATE TABLE "DEMO" (
"ID" NUMBER(4)  NOT NULL,
"NAME" VARCHAR2(20)  DEFAULT NULL,
"AGE" NUMBER(4)  DEFAULT 0 NOT NULL,
"SEX" CHAR(1)  DEFAULT 1 NOT NULL,
"MOBILE" VARCHAR2(20) DEFAULT NULL,
"REGTIME" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
"MEMO" CLOB,
PRIMARY KEY ("ID")
);
--创建索引
--添加注释
COMMENT ON COLUMN "DEMO"."ID" IS '序号';
COMMENT ON COLUMN "DEMO"."NAME" IS '姓名';
COMMENT ON COLUMN "DEMO"."AGE" IS '年龄';
COMMENT ON COLUMN "DEMO"."SEX" IS '性别';
COMMENT ON COLUMN "DEMO"."MOBILE" IS '电话';
COMMENT ON COLUMN "DEMO"."REGTIME" IS '时间';
COMMENT ON COLUMN "DEMO"."MEMO" IS '备注';

--建立序列
CREATE SEQUENCE DEMO_SQ;
--建立触发器，以设置自动增量字段的值
CREATE OR REPLACE TRIGGER DEMO_TR
BEFORE INSERT ON DEMO
FOR EACH ROW
DECLARE
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT DEMO_SQ.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;