CREATE TABLE "LOGCFG" (
"LOGNAME" VARCHAR2(20)  DEFAULT 'SYSTEM' NOT NULL,
"HOST" VARCHAR2(30)  DEFAULT NULL,
"DATEFORMATTER" VARCHAR2(20)  DEFAULT '[MM-dd HH:mm:ss]' NOT NULL,
"FILTER" VARCHAR2(400) DEFAULT NULL,
"WARNCLASS" VARCHAR2(80) DEFAULT NULL,
"WARNINTERAL" NUMBER(8) DEFAULT 0,
"LEVEL" NUMBER(1) DEFAULT 1,
"ADDLEVEL" CHAR(1) DEFAULT 1,
"ADDCLASSNAME" CHAR(1) DEFAULT 1,
"OUTCONSOLE" CHAR(1) DEFAULT 0,
"SYSLOGHOST" VARCHAR2(50)  DEFAULT NULL,
"SYSLOGFACILITY" VARCHAR2(10)  DEFAULT NULL,
"PARAMS" CLOB,
PRIMARY KEY ("LOGNAME", "HOST")
);
--添加注释
COMMENT ON COLUMN "LOGCFG"."LOGNAME" IS '日志目录';
COMMENT ON COLUMN "LOGCFG"."HOST" IS '主机';
COMMENT ON COLUMN "LOGCFG"."DATEFORMATTER" IS '时间格式';
COMMENT ON COLUMN "LOGCFG"."FILTER" IS '过滤器，正则表达式;符合条件一定输出';
COMMENT ON COLUMN "LOGCFG"."WARNCLASS" IS '报警接口实现类名';
COMMENT ON COLUMN "LOGCFG"."WARNINTERAL" IS '报警间隔，0不间隔，只要产生FATAL日志就报警';
COMMENT ON COLUMN "LOGCFG"."LEVEL" IS '日志级别，0DEBUG;1INFO;2WARN;3ERROR;4FATAL';
COMMENT ON COLUMN "LOGCFG"."ADDLEVEL" IS '日志里添加输出级别';
COMMENT ON COLUMN "LOGCFG"."ADDCLASSNAME" IS '日志里添加类名';
COMMENT ON COLUMN "LOGCFG"."OUTCONSOLE" IS '是否输出到控制台';
COMMENT ON COLUMN "LOGCFG"."SYSLOGHOST" IS 'linux.syslog服务器名';
COMMENT ON COLUMN "LOGCFG"."SYSLOGFACILITY" IS 'linux.syslog设备名';
COMMENT ON COLUMN "LOGCFG"."PARAMS" IS '配置信息';
