CREATE TABLE "SERVICES" (
"ID" NUMBER(8)  NOT NULL,
"HOST" VARCHAR2(30)  DEFAULT NULL,
"TITLE" VARCHAR2(60) DEFAULT NULL,
"CLASSNAME" VARCHAR2(80) DEFAULT NULL,
"PARAMS" CLOB,
"LOGNAME" VARCHAR2(20)  DEFAULT 'system' NOT NULL,
"STATUS" NUMBER(1)  DEFAULT 0 NOT NULL,
"MEMO" CLOB,
"CREATETIME" TIMESTAMP  DEFAULT CURRENT_TIMESTAMP NOT NULL,
PRIMARY KEY ("ID")
);
--创建索引
CREATE UNIQUE INDEX "IX_SERVICES_TITLE" ON "SERVICES" ("TITLE", "HOST");
CREATE INDEX "IX_SERVICES_CLASSNAME" ON "SERVICES" ("CLASSNAME");
CREATE INDEX "IX_SERVICES_STATUS" ON "SERVICES" ("STATUS");
CREATE INDEX "IX_SERVICES_CREATETIME" ON "SERVICES" ("CREATETIME");
--添加注释
COMMENT ON COLUMN "SERVICES"."ID" IS '服务标识';
COMMENT ON COLUMN "SERVICES"."HOST" IS '主机名';
COMMENT ON COLUMN "SERVICES"."TITLE" IS '注释';
COMMENT ON COLUMN "SERVICES"."CLASSNAME" IS '类名';
COMMENT ON COLUMN "SERVICES"."PARAMS" IS '配置';
COMMENT ON COLUMN "SERVICES"."LOGNAME" IS '日志目录';
COMMENT ON COLUMN "SERVICES"."STATUS" IS '0随服务启动 1手动 2禁用';
COMMENT ON COLUMN "SERVICES"."MEMO" IS '备注';
COMMENT ON COLUMN "SERVICES"."CREATETIME" IS '创建时间';
--建立序列
CREATE SEQUENCE SERVICES_SQ;

--建立触发器，以设置自动增量字段的值
CREATE OR REPLACE TRIGGER SERVICES_TR
BEFORE INSERT ON SERVICES
FOR EACH ROW
DECLARE
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT SERVICES_SQ.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;