CREATE TABLE "SOAPS" (
"ID" NUMBER(8)  NOT NULL,
"HOST" VARCHAR2(30)  DEFAULT NULL,
"TITLE" VARCHAR2(60)  DEFAULT NULL,
"SERVICENAME" VARCHAR2(30)  DEFAULT NULL,
"IMPLCLASS" VARCHAR2(80)  DEFAULT NULL,
"CLASSNAME" VARCHAR2(80)  DEFAULT NULL,
"AUTHTYPE" NUMBER(1)  DEFAULT 0 NOT NULL,
"STYLE" VARCHAR2(10)  DEFAULT 'RPC' NOT NULL,
"USETYPE" VARCHAR2(10)  DEFAULT 'LITERAL' NOT NULL,
"IPLIST" VARCHAR2(100) DEFAULT NULL,
"INFILTER" VARCHAR2(80) DEFAULT NULL,
"OUTFILTER" VARCHAR2(80) DEFAULT NULL,
"PARAMS" CLOB,
"AEGIS" CLOB,
"LOGNAME" VARCHAR2(20)  DEFAULT 'system' NOT NULL,
"MEMO" CLOB,
"CREATETIME" TIMESTAMP  DEFAULT CURRENT_TIMESTAMP NOT NULL,
PRIMARY KEY ("ID")
);
--创建索引
CREATE UNIQUE INDEX "IX_SOAPS_SERVICENAME" ON "SOAPS" ("HOST", "SERVICENAME");
CREATE UNIQUE INDEX "IX_SOAPS_TITLE" ON "SOAPS" ("HOST", "TITLE");
CREATE INDEX "IX_SOAPS_IMPLCLASS" ON "SOAPS" ("IMPLCLASS");
CREATE INDEX "IX_SOAPS_CLASSNAME" ON "SOAPS" ("CLASSNAME");
CREATE INDEX "IX_SOAPS_INFILTER" ON "SOAPS" ("INFILTER");
CREATE INDEX "IX_SOAPS_OUTFILTER" ON "SOAPS" ("OUTFILTER");
CREATE INDEX "IX_SOAPS_AUTHTYPE" ON "SOAPS" ("AUTHTYPE");
CREATE INDEX "IX_SOAPS_STYLE" ON "SOAPS" ("STYLE");
CREATE INDEX "IX_SOAPS_USETYPE" ON "SOAPS" ("USETYPE");
CREATE INDEX "IX_SOAPS_CREATETIME" ON "SOAPS" ("CREATETIME");
--添加注释
COMMENT ON COLUMN "SOAPS"."ID" IS '序号;SOAPID，服务ID';
COMMENT ON COLUMN "SOAPS"."HOST" IS '服务所属机器名';
COMMENT ON COLUMN "SOAPS"."TITLE" IS '服务标题';
COMMENT ON COLUMN "SOAPS"."SERVICENAME" IS '服务名，如MYSERVICE;则客户端访问的地址为:HTTP://LOCALHOST/SERVICES/MYSERVICE';
COMMENT ON COLUMN "SOAPS"."IMPLCLASS" IS '实现接口类中的函数声明(宽接口);如果CLASSNAME不是接口可以不填';
COMMENT ON COLUMN "SOAPS"."CLASSNAME" IS '包含公有函数提供给远端调用(窄接口)';
COMMENT ON COLUMN "SOAPS"."AUTHTYPE" IS '认证类型';
COMMENT ON COLUMN "SOAPS"."STYLE" IS '文档STYLE';
COMMENT ON COLUMN "SOAPS"."USETYPE" IS '文档USE';
COMMENT ON COLUMN "SOAPS"."IPLIST" IS 'IP验证（支持192.168.*.*），不填不验证';
COMMENT ON COLUMN "SOAPS"."INFILTER" IS '扩展SOAPFILTER/ABSTRACTHANDLER;在这里可以解压更改请求';
COMMENT ON COLUMN "SOAPS"."OUTFILTER" IS '扩展SOAPFILTER/ABSTRACTHANDLER;在这里可以压缩更改回应';
COMMENT ON COLUMN "SOAPS"."PARAMS" IS '配置文件内容';
COMMENT ON COLUMN "SOAPS"."AEGIS" IS '如果是WSDL优先设计;可以依此控制输入输出文档的NAMESPACE;PREFIX;NAME等';
COMMENT ON COLUMN "SOAPS"."LOGNAME" IS '日志目录';
COMMENT ON COLUMN "SOAPS"."MEMO" IS '备注';
COMMENT ON COLUMN "SOAPS"."CREATETIME" IS '创建时间';
--建立序列
CREATE SEQUENCE SOAPS_SQ;

--建立触发器，以设置自动增量字段的值
CREATE OR REPLACE TRIGGER SOAPS_TR
BEFORE INSERT ON SOAPS
FOR EACH ROW
DECLARE
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT SOAPS_SQ.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;