CREATE TABLE "SVNCODES" (
"ID" NUMBER(8)  NOT NULL,
"HOST" VARCHAR2(25)  DEFAULT 'localhost' NOT NULL,
"TITLE" VARCHAR2(50)  DEFAULT 'NEWPROJECT' NOT NULL,
"URL" VARCHAR2(200) DEFAULT NULL,
"DIRNAME" VARCHAR2(35)  DEFAULT 'NEWDIR' NOT NULL,
"USERNAME" VARCHAR2(20) DEFAULT NULL,
"PASSWORD" VARCHAR2(50) DEFAULT NULL,
"DIRTYPE" NUMBER(1)  DEFAULT 0 NOT NULL,
"MESSAGE" CLOB,
PRIMARY KEY ("ID")
);
--创建索引
CREATE UNIQUE INDEX "IX_SVNCODES_URL" ON "SVNCODES" ("HOST", "URL");
CREATE INDEX "IX_SVNCODES_TITLE" ON "SVNCODES" ("TITLE");
CREATE INDEX "IX_SVNCODES_DIRNAME" ON "SVNCODES" ("DIRNAME");
CREATE INDEX "IX_SVNCODES_DIRTYPE" ON "SVNCODES" ("DIRTYPE");
--添加注释
COMMENT ON COLUMN "SVNCODES"."ID" IS '序号';
COMMENT ON COLUMN "SVNCODES"."HOST" IS '所属机器名';
COMMENT ON COLUMN "SVNCODES"."TITLE" IS '工程代码标题';
COMMENT ON COLUMN "SVNCODES"."URL" IS 'SVN资源地址';
COMMENT ON COLUMN "SVNCODES"."DIRNAME" IS '本地目录';
COMMENT ON COLUMN "SVNCODES"."USERNAME" IS 'SVN认证帐号';
COMMENT ON COLUMN "SVNCODES"."PASSWORD" IS 'SVN认证密码';
COMMENT ON COLUMN "SVNCODES"."DIRTYPE" IS '目录类型，0.JAVA源码 1WEB目录（JSP）';
COMMENT ON COLUMN "SVNCODES"."MESSAGE" IS '更新信息';
--建立序列
CREATE SEQUENCE SVNCODES_SQ;
--建立触发器，以设置自动增量字段的值
CREATE OR REPLACE TRIGGER SVNCODES_TR
BEFORE INSERT ON SVNCODES
FOR EACH ROW
DECLARE
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT SVNCODES_SQ.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;