CREATE TABLE "WEBDIRECTORY" (
"ID" NUMBER(8)  NOT NULL,
"HOST" VARCHAR2(30)  DEFAULT NULL,
"DIRNAME" VARCHAR2(20)  DEFAULT NULL,
"TITLE" VARCHAR2(60) DEFAULT NULL,
"CLASSNAME" VARCHAR2(80) DEFAULT NULL,
"DEFAULTPAGE" VARCHAR2(20) DEFAULT NULL,
"IPLIST" VARCHAR2(100) DEFAULT NULL,
"LOGINTYPE" NUMBER(1)  DEFAULT 0 NOT NULL,
"PARAMS" CLOB,
"LOGNAME" VARCHAR2(20)  DEFAULT 'system' NOT NULL,
"CHARSET" VARCHAR2(20) DEFAULT NULL,
"MEMO" CLOB,
"CREATETIME" TIMESTAMP  DEFAULT CURRENT_TIMESTAMP NOT NULL,
PRIMARY KEY ("ID")
);
--创建索引
CREATE UNIQUE INDEX "IX_WEBDIRECTORY_DIRNAME" ON "WEBDIRECTORY" ("DIRNAME", "HOST");
CREATE INDEX "IX_WEBDIRECTORY_TITLE" ON "WEBDIRECTORY" ("TITLE");
CREATE INDEX "IX_WEBDIRECTORY_CLASSNAME" ON "WEBDIRECTORY" ("CLASSNAME");
CREATE INDEX "IX_WEBDIRECTORY_LOGINTYPE" ON "WEBDIRECTORY" ("LOGINTYPE");
CREATE INDEX "IX_WEBDIRECTORY_CREATETIME" ON "WEBDIRECTORY" ("CREATETIME");
--添加注释
COMMENT ON COLUMN "WEBDIRECTORY"."ID" IS '目录标识';
COMMENT ON COLUMN "WEBDIRECTORY"."HOST" IS '主机';
COMMENT ON COLUMN "WEBDIRECTORY"."DIRNAME" IS '目录名';
COMMENT ON COLUMN "WEBDIRECTORY"."TITLE" IS '注释';
COMMENT ON COLUMN "WEBDIRECTORY"."CLASSNAME" IS '类名';
COMMENT ON COLUMN "WEBDIRECTORY"."DEFAULTPAGE" IS '首页';
COMMENT ON COLUMN "WEBDIRECTORY"."IPLIST" IS '需要验证IP，NULL不验证';
COMMENT ON COLUMN "WEBDIRECTORY"."LOGINTYPE" IS '认证类型，0禁止访问，1需要登录，2不需登录，3公共目录;4需要BASIC认证';
COMMENT ON COLUMN "WEBDIRECTORY"."PARAMS" IS '配置';
COMMENT ON COLUMN "WEBDIRECTORY"."LOGNAME" IS '日志目录';
COMMENT ON COLUMN "WEBDIRECTORY"."CHARSET" IS 'HTTP请求编码';
COMMENT ON COLUMN "WEBDIRECTORY"."MEMO" IS '备注';
COMMENT ON COLUMN "WEBDIRECTORY"."CREATETIME" IS '创建/修改时间';
--建立序列
CREATE SEQUENCE WEBDIRECTORY_SQ;
--建立触发器，以设置自动增量字段的值
CREATE OR REPLACE TRIGGER WEBDIRECTORY_TR
BEFORE INSERT ON WEBDIRECTORY
FOR EACH ROW
DECLARE
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT WEBDIRECTORY_SQ.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;