CREATE TABLE "WEBUSER" (
"ID" NUMBER(8)  NOT NULL,
"DIRID" NUMBER(8)  DEFAULT 0 NOT NULL,
"SOAPID" NUMBER(8) DEFAULT 0,
"USERNAME" VARCHAR2(30)  DEFAULT NULL,
"PASSWORD" VARCHAR2(30)  DEFAULT NULL,
"REALNAME" VARCHAR2(30) DEFAULT NULL,
"USERGROUP" VARCHAR2(30) DEFAULT NULL,
"MOBILE" VARCHAR2(30) DEFAULT NULL,
"EMAIL" VARCHAR2(60) DEFAULT NULL,
"PERMISSION" VARCHAR2(50) DEFAULT NULL,
"STIMEOUT" NUMBER(8)  DEFAULT 0 NOT NULL,
"ISACTIVE" CHAR(1)  DEFAULT 1 NOT NULL,
"IPLIST" VARCHAR2(100) DEFAULT NULL,
"EXTPARAMS" VARCHAR2(60) DEFAULT NULL,
"LOGINTIME" TIMESTAMP,
"MEMO" CLOB,
"CREATETIME" TIMESTAMP  DEFAULT CURRENT_TIMESTAMP NOT NULL,
PRIMARY KEY ("ID")
);
--创建索引
CREATE UNIQUE INDEX "IX_WEBUSER_USERNAME" ON "WEBUSER" ("USERNAME");
CREATE INDEX "IX_WEBUSER_REALNAME" ON "WEBUSER" ("REALNAME");
CREATE INDEX "IX_WEBUSER_USERGROUP" ON "WEBUSER" ("USERGROUP");
CREATE INDEX "IX_WEBUSER_MOBILE" ON "WEBUSER" ("MOBILE");
CREATE INDEX "IX_WEBUSER_EMAIL" ON "WEBUSER" ("EMAIL");
CREATE INDEX "IX_WEBUSER_ISACTIVE" ON "WEBUSER" ("ISACTIVE");
CREATE INDEX "IX_WEBUSER_LOGINTIME" ON "WEBUSER" ("LOGINTIME");
CREATE INDEX "IX_WEBUSER_EXTPARAMS" ON "WEBUSER" ("EXTPARAMS");
CREATE INDEX "IX_WEBUSER_DIRID" ON "WEBUSER" ("DIRID");
CREATE INDEX "IX_WEBUSER_SOAPID" ON "WEBUSER" ("SOAPID");
--添加注释
COMMENT ON COLUMN "WEBUSER"."ID" IS '标识';
COMMENT ON COLUMN "WEBUSER"."DIRID" IS 'WEB服务ID，内置目录（0=CONSOLE;-1=SERVICES）';
COMMENT ON COLUMN "WEBUSER"."SOAPID" IS 'SOAP服务ID;DIRID=-1（SERVICES目录）时有效';
COMMENT ON COLUMN "WEBUSER"."USERNAME" IS '用户名';
COMMENT ON COLUMN "WEBUSER"."PASSWORD" IS '密码';
COMMENT ON COLUMN "WEBUSER"."REALNAME" IS '真实名称';
COMMENT ON COLUMN "WEBUSER"."USERGROUP" IS '组名，由具体WEB服务定义';
COMMENT ON COLUMN "WEBUSER"."MOBILE" IS '手机号';
COMMENT ON COLUMN "WEBUSER"."EMAIL" IS '邮箱';
COMMENT ON COLUMN "WEBUSER"."PERMISSION" IS '权限，由具体WEB服务定义，如：CONSOLE目录，由10位数字组成字符串表示';
COMMENT ON COLUMN "WEBUSER"."STIMEOUT" IS '对话超时，0默认值=SERVLET容器定义的值';
COMMENT ON COLUMN "WEBUSER"."ISACTIVE" IS '1激活0停用';
COMMENT ON COLUMN "WEBUSER"."IPLIST" IS '不填不验证IP，否则只允许指定IP访问，;隔开如：192.168.*.*;211.232.*.*';
COMMENT ON COLUMN "WEBUSER"."EXTPARAMS" IS '预留字段';
COMMENT ON COLUMN "WEBUSER"."LOGINTIME" IS '最后登录时间';
COMMENT ON COLUMN "WEBUSER"."MEMO" IS '备注';
COMMENT ON COLUMN "WEBUSER"."CREATETIME" IS '创建时间';
--建立序列
CREATE SEQUENCE WEBUSER_SQ;
--建立触发器，以设置自动增量字段的值
CREATE OR REPLACE TRIGGER WEBUSER_TR
BEFORE INSERT ON WEBUSER
FOR EACH ROW
DECLARE
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT WEBUSER_SQ.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;