CREATE TABLE `demo` (
  `id` INTEGER(4) NOT NULL AUTO_INCREMENT COMMENT '序号',
  `name` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '姓名',
  `age` INTEGER(4) NOT NULL DEFAULT 0 COMMENT '年龄',
  `sex` BIT(1) NOT NULL DEFAULT 1 COMMENT '性别',
  `mobile` VARCHAR(20) DEFAULT NULL COMMENT '电话',
  `regtime` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '时间',
  `memo` TEXT COMMENT '备注',
  PRIMARY KEY (`id`)
);