CREATE TABLE `soaps` (
  `id` INTEGER(8) NOT NULL AUTO_INCREMENT COMMENT '序号,SoapID，服务id',
  `host` VARCHAR(30) NOT NULL DEFAULT '' COMMENT '服务所属机器名',
  `title` VARCHAR(60) NOT NULL DEFAULT '' COMMENT '服务标题',
  `servicename` VARCHAR(30) NOT NULL DEFAULT '' COMMENT '服务名，如myservice,则客户端访问的地址为:http://localhost/services/myservice',
  `implclass` VARCHAR(80) NOT NULL DEFAULT '' COMMENT '实现接口类中的函数声明(宽接口),如果className不是接口可以不填',
  `classname` VARCHAR(80) NOT NULL DEFAULT '' COMMENT '包含公有函数提供给远端调用(窄接口)',
  `authtype` TINYINT(2) NOT NULL DEFAULT 0 COMMENT '认证类型',
  `style` VARCHAR(10) NOT NULL DEFAULT 'rpc' COMMENT '文档style',
  `usetype` VARCHAR(10) NOT NULL DEFAULT 'literal' COMMENT '文档use',
  `iplist` VARCHAR(100) DEFAULT NULL COMMENT 'ip验证（支持192.168.*.*），不填不验证',
  `infilter` VARCHAR(80) DEFAULT NULL COMMENT '扩展SoapFilter/AbstractHandler,在这里可以解压更改请求',
  `outfilter` VARCHAR(80) DEFAULT NULL COMMENT '扩展SoapFilter/AbstractHandler,在这里可以压缩更改回应',
  `params` TEXT COMMENT '配置文件内容',
  `aegis` TEXT COMMENT '如果是WSDL优先设计,可以依此控制输入输出文档的Namespace,Prefix,name等',
  `logname` VARCHAR(20) NOT NULL DEFAULT 'system' COMMENT '日志目录',
  `memo` TEXT COMMENT '备注',
  `createtime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `servicename` (`host`, `servicename`),
  UNIQUE KEY `title` (`host`, `title`),
  KEY `implclass` (`implclass`),
  KEY `classname` (`classname`),
  KEY `infilter` (`infilter`),
  KEY `outfilter` (`outfilter`),
  KEY `authtype` (`authtype`),
  KEY `style` (`style`),
  KEY `usetype` (`usetype`),
  KEY `createtime` (`createtime`)
);